import httpx
from openai import OpenAI
from app.core.config import settings
from app.services.storage_service import StorageService
from app.services.image_processing import ImageProcessingService
from app.core.exceptions import AuraException
from fastapi import status
import structlog
from sqlmodel import Session
from app.models.image import Image

logger = structlog.get_logger()
client = OpenAI(api_key=settings.OPENAI_API_KEY)

class AIChatService:
    def __init__(self, session: Session, storage_service: StorageService, image_processor: ImageProcessingService):
        self.session = session
        self.storage = storage_service
        self.processor = image_processor

    async def process_instruction(self, instruction: str, base_image_url: str = None) -> dict:
        """
        Interprets natural language via OpenAI, generates an image via DALL-E 3, 
        optimizes it via Pillow, and saves it to R2.
        """
        logger.info("ai_instruction_received", instruction=instruction)
        
        try:
            # 1. Generate Image using OpenAI DALL-E 3
            # If base_image_url is provided, we could technically do Image Variation/Editing,
            # but DALL-E 3 currently supports generation best. 
            response = client.images.generate(
                model="dall-e-3",
                prompt=instruction,
                size="1024x1024",
                quality="standard",
                n=1,
            )
            openai_image_url = response.data[0].url
            
            # 2. Download the image generated by OpenAI
            async with httpx.AsyncClient() as http_client:
                img_resp = await http_client.get(openai_image_url)
                if img_resp.status_code != 200:
                    raise ValueError("Failed to download image from OpenAI")
                raw_image_bytes = img_resp.content

            # 3. Process & Compress using Pillow (Convert to WEBP)
            optimized_bytes, mime_type = self.processor.process_and_compress(raw_image_bytes)
            
            # 4. Save to Cloudflare R2 directly (using boto3 put_object via storage_service)
            import uuid
            image_id = str(uuid.uuid4())[:8]
            object_name = f"{image_id}.webp"
            
            self.storage.s3_client.put_object(
                Bucket=self.storage.bucket,
                Key=object_name,
                Body=optimized_bytes,
                ContentType=mime_type
            )
            
            public_url = f"{settings.R2_PUBLIC_URL_PREFIX}/{object_name}"
            
            # 5. Save to Database
            db_image = Image(
                id=image_id,
                url=public_url,
                mime_type=mime_type,
                size=len(optimized_bytes),
                is_public=True
            )
            self.session.add(db_image)
            self.session.commit()
            
            return {
                "message": "I've successfully generated and saved your image!",
                "generated_image_url": public_url,
                "image_id": image_id
            }

        except Exception as e:
            logger.error("ai_chat_error", error=str(e))
            raise AuraException("Failed to process AI instruction. Please try again.", status.HTTP_500_INTERNAL_SERVER_ERROR)
